// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBexK408eKgEVJhIjvCQNV9HPUyS_2Mr6c',
    appId: '1:886353618874:web:6413af79db42f0168c1f83',
    messagingSenderId: '886353618874',
    projectId: 'flutter-fitsnap',
    authDomain: 'flutter-fitsnap.firebaseapp.com',
    storageBucket: 'flutter-fitsnap.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyBcdAAsuJrdOTpgbslCpZnK73kFrRT-0',
    appId: '1:886353618874:android:7ee4b2608a6731e08c1f83',
    messagingSenderId: '886353618874',
    projectId: 'flutter-fitsnap',
    storageBucket: 'flutter-fitsnap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX-Gi3s7JRz1o-0-YXaTnPEPsqskkWzm8',
    appId: '1:886353618874:ios:72c95484a7edf7488c1f83',
    messagingSenderId: '886353618874',
    projectId: 'flutter-fitsnap',
    storageBucket: 'flutter-fitsnap.firebasestorage.app',
    iosBundleId: 'com.example.flutterFitsnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX-Gi3s7JRz1o-0-YXaTnPEPsqskkWzm8',
    appId: '1:886353618874:ios:72c95484a7edf7488c1f83',
    messagingSenderId: '886353618874',
    projectId: 'flutter-fitsnap',
    storageBucket: 'flutter-fitsnap.firebasestorage.app',
    iosBundleId: 'com.example.flutterFitsnap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBexK408eKgEVJhIjvCQNV9HPUyS_2Mr6c',
    appId: '1:886353618874:web:44e24b6b2ad11e3d8c1f83',
    messagingSenderId: '886353618874',
    projectId: 'flutter-fitsnap',
    authDomain: 'flutter-fitsnap.firebaseapp.com',
    storageBucket: 'flutter-fitsnap.firebasestorage.app',
  );

}